# Generated by Django 5.1.6 on 2026-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_income_limit', models.DecimalField(decimal_places=2, help_text='Maximum annual income allowed', max_digits=10)),
                ('allowed_ration_card', models.CharField(choices=[('BPL', 'BPL Only'), ('ALL', 'All (APL & BPL)')], default='ALL', max_length=10)),
                ('allowed_category', models.CharField(choices=[('ALL', 'All Categories'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('General', 'General')], default='ALL', max_length=20)),
                ('benefits', models.TextField(help_text='What benefits the user gets')),
            ],
        ),
    ]
