# Generated by Django 5.1.6 on 2026-08-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0003_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='remarks',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='token_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
