# Generated by Django 5.1.6 on 2026-08-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0004_remove_application_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='allowed_category',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='allowed_ration_card',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='max_income_limit',
        ),
        migrations.AddField(
            model_name='scheme',
            name='allowed_ration_cards',
            field=models.CharField(default='APL,BPL', max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='scheme',
            name='max_income',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='scheme',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheme',
            name='required_documents',
            field=models.CharField(default='Aadhaar Card, Income Certificate', help_text='Comma separated list of required documents', max_length=300),
        ),
    ]
