# Generated by Django 5.1.6 on 2026-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0005_remove_scheme_allowed_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='allowed_gender',
            field=models.CharField(default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='required_documents',
            field=models.CharField(default='Aadhaar Card, Income Certificate', max_length=300),
        ),
    ]
