# Generated by Django 5.1.6 on 2026-08-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0006_scheme_allowed_gender_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='required_occupation',
            field=models.CharField(choices=[('ALL', 'ALL (Any Occupation)'), ('Farmer', 'Farmer'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='ALL', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='allowed_gender',
            field=models.CharField(choices=[('ALL', 'ALL (Everyone)'), ('Female', 'Female Only'), ('Male', 'Male Only')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='allowed_ration_cards',
            field=models.CharField(choices=[('ALL', 'ALL (APL & BPL)'), ('APL', 'APL Only'), ('BPL', 'BPL Only')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('ALL', 'ALL Categories'), ('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='ALL', max_length=20),
        ),
    ]
