# Generated by Django 5.1.6 on 2026-08-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0007_scheme_required_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='extra_fields',
            field=models.CharField(blank=True, default='', help_text='അഡീഷണൽ ചോദ്യങ്ങൾ കോമ (,) ഇട്ട് എഴുതുക.', max_length=500),
        ),
    ]
