# Generated by Django 5.1.6 on 2026-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0008_scheme_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant_phone',
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='staff_remarks',
            field=models.TextField(blank=True, default='Documents submitted. Awaiting verification.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted (Pending Verification)'), ('Under Verification', 'Under Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='token_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
