# Generated by Django 5.1.6 on 2026-08-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0009_remove_application_applicant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted to Akshaya'), ('Under Verification', 'Under Verification'), ('Forwarded to Govt', 'Forwarded to Govt Dept'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=30),
        ),
    ]
