# Generated by Django 5.1.6 on 2026-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0010_application_form_data_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_differently_abled',
            field=models.BooleanField(default=False),
        ),
    ]
