# Generated by Django 5.1.6 on 2026-08-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0011_userprofile_is_differently_abled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='is_for_disabled_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='required_documents',
            field=models.CharField(default='Identity Card, Income Certificate', max_length=300),
        ),
    ]
