# Generated by Django 5.1.6 on 2026-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0012_scheme_is_for_disabled_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disability_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disability_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='required_documents',
            field=models.CharField(default='Identity Card, Income Certificate', help_text='ആവശ്യമുള്ള രേഖകൾ കോമ (,) ഇട്ട് നൽകുക.', max_length=300),
        ),
    ]
