# Generated by Django 5.1.6 on 2026-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0013_userprofile_disability_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='allowed_marital_status',
            field=models.CharField(choices=[('ALL', 'ALL (Married & Unmarried)'), ('Single', 'Single Only'), ('Married', 'Married Only'), ('Divorced', 'Divorced Only'), ('Widow', 'Widow/Widower Only')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single (Unmarried)'), ('Married', 'Married'), ('Divorced', 'Divorced '), ('Widow', 'Widow/Widower')], max_length=20, null=True),
        ),
    ]
