# Generated by Django 5.1.6 on 2026-08-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0015_applicationdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='document',
        ),
    ]
