# Generated by Django 5.1.6 on 2026-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0016_remove_application_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='govt_ref_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='staff_remarks',
            field=models.TextField(blank=True, default='Application submitted. Awaiting verification.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Document Verification'), ('REJECTED_DOCS', 'Documents Rejected (Re-upload Needed)'), ('DOCS_APPROVED', 'Documents Approved (Eligible for Token)'), ('TOKEN_BOOKED', 'Token Booked / Waiting in Queue'), ('IN_PROGRESS', 'Processing at Counter'), ('FORWARDED_TO_GOVT', 'Submitted to Govt Portal')], default='PENDING_VERIFICATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='token_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single (Unmarried)'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow/Widower')], max_length=20, null=True),
        ),
    ]
