# Generated by Django 5.1.6 on 2026-08-30 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0017_application_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='govt_ref_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='staff_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Document Verification'), ('DOCS_APPROVED', 'Documents Approved (Eligible for Token)'), ('REJECTED_DOCS', 'Documents Rejected'), ('TOKEN_BOOKED', 'Token Booked'), ('IN_PROGRESS', 'Processing at Counter'), ('FORWARDED_TO_GOVT', 'Forwarded to Govt Portal')], default='PENDING_VERIFICATION', max_length=30),
        ),
    ]
