# Generated by Django 5.1.6 on 2026-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0018_alter_application_application_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
