# Generated by Django 5.1.6 on 2026-09-04 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0020_application_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(default='APP123456', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='govt_ref_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='welfare_app.scheme'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Akshaya Verification'), ('REJECTED_DOCS', 'Rejected - Reupload Required'), ('DOCS_APPROVED', 'Approved - Book Appointment'), ('TOKEN_BOOKED', 'Token Booked - Waiting in Queue'), ('IN_PROGRESS', 'At Counter - Processing'), ('FORWARDED_TO_GOVT', 'Submitted to Government Portal')], default='PENDING_VERIFICATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', related_query_name='documents', to='welfare_app.application'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(upload_to='application_docs/'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='allowed_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('ALL', 'All Genders')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='allowed_marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow/Widower'), ('DIVORCED', 'Divorced'), ('ALL', 'All Statuses')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='allowed_ration_cards',
            field=models.CharField(choices=[('AY', 'Antyodaya Anna Yojana (Yellow/Manja)'), ('PHH', 'Priority Household (Pink)'), ('NPS', 'Non-Priority State (Blue)'), ('NPNS', 'Non-Priority Non-State (White)'), ('ALL', 'All Ration Cards')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('ALL', 'All Categories')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='extra_fields',
            field=models.TextField(blank=True, help_text='Comma separated custom input field names'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='max_income',
            field=models.DecimalField(decimal_places=2, default=999999, max_digits=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='required_documents',
            field=models.TextField(blank=True, help_text='Comma separated document names (e.g., Aadhaar, Income Certificate)'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='required_occupation',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('STUDENT', 'Student'), ('FISHERMAN', 'Fisherman'), ('EX_SERVICE', 'Ex-Serviceman'), ('UNEMPLOYED', 'Unemployed'), ('SELF_EMPLOYED', 'Self Employed'), ('OTHER', 'Other'), ('ALL', 'All Occupations')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('ALL', 'All Categories')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('ALL', 'All Genders')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow/Widower'), ('DIVORCED', 'Divorced'), ('ALL', 'All Statuses')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('STUDENT', 'Student'), ('FISHERMAN', 'Fisherman'), ('EX_SERVICE', 'Ex-Serviceman'), ('UNEMPLOYED', 'Unemployed'), ('SELF_EMPLOYED', 'Self Employed'), ('OTHER', 'Other'), ('ALL', 'All Occupations')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ration_card_type',
            field=models.CharField(blank=True, choices=[('AY', 'Antyodaya Anna Yojana (Yellow/Manja)'), ('PHH', 'Priority Household (Pink)'), ('NPS', 'Non-Priority State (Blue)'), ('NPNS', 'Non-Priority Non-State (White)'), ('ALL', 'All Ration Cards')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
