# Generated by Django 5.1.6 on 2026-09-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0021_scheme_department_alter_application_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='welfare_app.application'),
        ),
    ]
